#!/bin/bash
# ForgeTeam integration test: forge init
# Tests that forge init correctly detects project and generates files

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
TEST_DIR=$(mktemp -d)
errors=0

cleanup() {
  rm -rf "$TEST_DIR"
}
trap cleanup EXIT

assert_file_exists() {
  if [ ! -f "$1" ]; then
    echo "FAIL: expected file $1"
    ((errors++))
  fi
}

assert_dir_exists() {
  if [ ! -d "$1" ]; then
    echo "FAIL: expected directory $1"
    ((errors++))
  fi
}

assert_contains() {
  local file="$1" pattern="$2"
  if ! grep -q "$pattern" "$file" 2>/dev/null; then
    echo "FAIL: $file does not contain '$pattern'"
    ((errors++))
  fi
}

echo "ForgeTeam Integration Test: forge init"
echo "══════════════════════════════════════"

# Setup: simulate a Next.js project
echo "Setting up test project..."
mkdir -p "$TEST_DIR/test-project"
cd "$TEST_DIR/test-project"
git init -q

cat > package.json <<'EOF'
{
  "name": "test-app",
  "version": "2.1.0",
  "dependencies": {
    "next": "^14.0.0",
    "react": "^18.0.0"
  }
}
EOF
touch package-lock.json

# Setup: install forge to temp location
export FORGE_HOME="$TEST_DIR/forgeteam-home"
mkdir -p "$FORGE_HOME/skills"
mkdir -p "$FORGE_HOME/adapters"
cp "$PROJECT_ROOT/forge" "$FORGE_HOME/forge"
cp -r "$PROJECT_ROOT/skills"/* "$FORGE_HOME/skills/"
cp "$PROJECT_ROOT/adapters"/* "$FORGE_HOME/adapters/"

# Run forge init
echo "Running forge init..."
echo "y" | bash "$FORGE_HOME/forge" init > /dev/null 2>&1 || true

echo ""
echo "Checking results..."

# Test: directory structure
assert_dir_exists ".forgeteam"
assert_dir_exists ".forgeteam/memory"
assert_dir_exists "specs/active"
assert_dir_exists "specs/archived"

# Test: config.yaml
assert_file_exists ".forgeteam/config.yaml"
assert_contains ".forgeteam/config.yaml" 'language: "typescript"'
assert_contains ".forgeteam/config.yaml" 'framework: "next"'
assert_contains ".forgeteam/config.yaml" 'name: "test-app"'

# Test: project-map.md
assert_file_exists ".forgeteam/memory/project-map.md"
assert_contains ".forgeteam/memory/project-map.md" "Next.js"
assert_contains ".forgeteam/memory/project-map.md" "npm"

# Test: CLAUDE.md (generated by adapter)
assert_file_exists "CLAUDE.md"
assert_contains "CLAUDE.md" "html-prototype"
assert_contains "CLAUDE.md" "quality-gate"
assert_contains "CLAUDE.md" "safety-guard"
assert_contains "CLAUDE.md" "learn"
assert_contains "CLAUDE.md" "evolve"

# Test: .claude/commands
assert_dir_exists ".claude/commands"
cmd_count=$(find .claude/commands -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
if [ "$cmd_count" -lt 13 ]; then
  echo "FAIL: expected >= 13 command files, got $cmd_count"
  ((errors++))
fi

# Test: .gitignore updated
assert_file_exists ".gitignore"
assert_contains ".gitignore" "forgeteam"

echo ""
echo "══════════════════════════════════════"
if [ $errors -eq 0 ]; then
  echo "✓ All init tests passed"
  exit 0
else
  echo "✗ $errors test(s) failed"
  exit 1
fi
